// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package pb

import (
	context "context"
	fmt "fmt"
	pmongo "github.com/amsokol/mongo-go-driver-protobuf/pmongo"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserID struct {
	Id                   *pmongo.ObjectId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-" bson:"-"`
	XXX_unrecognized     []byte           `json:"-" bson:"-"`
	XXX_sizecache        int32            `json:"-" bson:"-"`
}

func (m *UserID) Reset()         { *m = UserID{} }
func (m *UserID) String() string { return proto.CompactTextString(m) }
func (*UserID) ProtoMessage()    {}
func (*UserID) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *UserID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserID.Unmarshal(m, b)
}
func (m *UserID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserID.Marshal(b, m, deterministic)
}
func (m *UserID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserID.Merge(m, src)
}
func (m *UserID) XXX_Size() int {
	return xxx_messageInfo_UserID.Size(m)
}
func (m *UserID) XXX_DiscardUnknown() {
	xxx_messageInfo_UserID.DiscardUnknown(m)
}

var xxx_messageInfo_UserID proto.InternalMessageInfo

func (m *UserID) GetId() *pmongo.ObjectId {
	if m != nil {
		return m.Id
	}
	return nil
}

type UserInfo struct {
	Id                   *pmongo.ObjectId     `protobuf:"bytes,1,opt,name=id,proto3" json:"_id,omitempty" bson:"_id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty" bson:"createdAt,omitempty"`
	ModifiedAt           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=modifiedAt,proto3" json:"modifiedAt,omitempty" bson:"modifiedAt,omitempty"`
	FirstName            string               `protobuf:"bytes,4,opt,name=firstName,proto3" json:"firstName,omitempty" bson:"firstName,omitempty"`
	LastName             string               `protobuf:"bytes,5,opt,name=lastName,proto3" json:"lastName,omitempty" bson:"lastName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetId() *pmongo.ObjectId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *UserInfo) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *UserInfo) GetModifiedAt() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedAt
	}
	return nil
}

func (m *UserInfo) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserInfo) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type Res struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Count                uint32   `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Res) Reset()         { *m = Res{} }
func (m *Res) String() string { return proto.CompactTextString(m) }
func (*Res) ProtoMessage()    {}
func (*Res) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *Res) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Res.Unmarshal(m, b)
}
func (m *Res) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Res.Marshal(b, m, deterministic)
}
func (m *Res) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Res.Merge(m, src)
}
func (m *Res) XXX_Size() int {
	return xxx_messageInfo_Res.Size(m)
}
func (m *Res) XXX_DiscardUnknown() {
	xxx_messageInfo_Res.DiscardUnknown(m)
}

var xxx_messageInfo_Res proto.InternalMessageInfo

func (m *Res) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Res) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Res) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Res) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*UserID)(nil), "pb.UserID")
	proto.RegisterType((*UserInfo)(nil), "pb.UserInfo")
	proto.RegisterType((*Res)(nil), "pb.Res")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x6b, 0xdb, 0x30,
	0x14, 0xc6, 0x69, 0xdc, 0xd6, 0xf1, 0x6b, 0x07, 0x43, 0x8c, 0xe1, 0xb9, 0xd0, 0x1a, 0x9f, 0xb6,
	0x31, 0x14, 0xe8, 0x6e, 0x85, 0x1d, 0x52, 0x36, 0x46, 0x2e, 0x5d, 0x31, 0xdb, 0x61, 0x30, 0x08,
	0xb2, 0x2d, 0x7b, 0x2a, 0xb6, 0x25, 0x24, 0x85, 0x90, 0xfb, 0xfe, 0x80, 0x9d, 0x77, 0xd8, 0xdf,
	0x3a, 0x4b, 0x8a, 0x1d, 0x67, 0x0b, 0xeb, 0xcd, 0x7a, 0xdf, 0xf7, 0xfd, 0xfc, 0xde, 0x93, 0x20,
	0x20, 0x82, 0x61, 0x21, 0xb9, 0xe6, 0x68, 0x22, 0xb2, 0xe8, 0xaa, 0xe2, 0xbc, 0xaa, 0xe9, 0xcc,
	0x56, 0xb2, 0x55, 0x39, 0xd3, 0xac, 0xa1, 0x4a, 0x93, 0x46, 0x38, 0x53, 0x74, 0xf1, 0xb7, 0x81,
	0x36, 0x42, 0x6f, 0xb6, 0x62, 0xa8, 0xbf, 0x33, 0x59, 0x2c, 0x05, 0x91, 0x7a, 0x33, 0xd3, 0xa4,
	0xaa, 0xa8, 0x3c, 0xa4, 0x88, 0x86, 0xb7, 0x15, 0x77, 0x4a, 0xf2, 0x1a, 0x4e, 0xbf, 0x28, 0x2a,
	0x17, 0xef, 0x51, 0x0c, 0x13, 0x56, 0x84, 0x47, 0xf1, 0xd1, 0xcb, 0xb3, 0xeb, 0xa7, 0x78, 0x6b,
	0xfa, 0x94, 0x3d, 0xd0, 0x5c, 0x2f, 0x8a, 0xb4, 0xd3, 0x92, 0x9f, 0x1e, 0x4c, 0xad, 0xb9, 0x2d,
	0x39, 0xba, 0xff, 0x9f, 0xfd, 0x16, 0xff, 0xfa, 0xf1, 0xdb, 0x7b, 0xf5, 0xa0, 0x78, 0x7b, 0x93,
	0x2c, 0x59, 0xf1, 0x86, 0x37, 0x4c, 0xdb, 0x56, 0x93, 0x38, 0x3b, 0x50, 0x34, 0x78, 0xf4, 0x15,
	0x82, 0x5c, 0x52, 0xa2, 0x69, 0x31, 0xd7, 0xe1, 0xc4, 0x82, 0x23, 0xec, 0xe6, 0xc5, 0xfd, 0xbc,
	0xf8, 0x73, 0xbf, 0x90, 0xdb, 0x2b, 0xf3, 0x8b, 0xc8, 0xd1, 0x86, 0xdc, 0x98, 0xb9, 0xa3, 0xa1,
	0x6f, 0x00, 0x0d, 0x2f, 0x58, 0xc9, 0x2c, 0xdb, 0x7b, 0x94, 0x1d, 0x1b, 0xf6, 0x85, 0x63, 0xef,
	0x82, 0x63, 0xf8, 0x88, 0x87, 0xde, 0x41, 0x50, 0x32, 0xa9, 0xf4, 0x1d, 0x69, 0x68, 0x78, 0xdc,
	0xc1, 0x83, 0xbd, 0xe6, 0x06, 0x6d, 0xaf, 0xb9, 0xa1, 0x8a, 0x6e, 0x60, 0x5a, 0x93, 0x6d, 0xfa,
	0xc4, 0xa6, 0x2f, 0x4d, 0xfa, 0x85, 0x4b, 0xf7, 0xd2, 0x38, 0x3c, 0xf8, 0x93, 0x25, 0x78, 0x29,
	0x55, 0x28, 0x04, 0x5f, 0xad, 0xf2, 0x9c, 0x2a, 0x65, 0x6f, 0x64, 0x9a, 0xf6, 0x47, 0xf4, 0x0c,
	0x4e, 0xa8, 0x94, 0x5c, 0xda, 0x85, 0x06, 0xa9, 0x3b, 0x98, 0x6a, 0xce, 0x57, 0xad, 0x5b, 0xc5,
	0x93, 0xd4, 0x1d, 0x10, 0x82, 0xe3, 0x82, 0x68, 0x62, 0x47, 0x38, 0x4f, 0xed, 0xf7, 0xf5, 0x1a,
	0xbc, 0xf9, 0xfd, 0x02, 0x5d, 0x82, 0xff, 0x91, 0x6a, 0x73, 0xf9, 0x08, 0xb0, 0xc8, 0xb0, 0x7b,
	0x33, 0x91, 0x6f, 0xbe, 0x4d, 0x03, 0x31, 0xf8, 0x77, 0x74, 0x6d, 0xf5, 0xf3, 0x41, 0xef, 0x9e,
	0xc9, 0xce, 0x81, 0xe1, 0xac, 0x23, 0xcc, 0xeb, 0xda, 0x48, 0x0a, 0x3d, 0xff, 0x67, 0xfb, 0x1f,
	0xcc, 0x6c, 0x83, 0x3f, 0x3b, 0xb5, 0xc2, 0xdb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x06, 0x71,
	0x51, 0x5b, 0x22, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	GetUser(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Res, error)
	NewUser(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*Res, error)
	GetAllUsers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Res, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) GetUser(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/pb.API/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) NewUser(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/pb.API/NewUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetAllUsers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/pb.API/GetAllUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	GetUser(context.Context, *UserID) (*Res, error)
	NewUser(context.Context, *UserInfo) (*Res, error)
	GetAllUsers(context.Context, *empty.Empty) (*Res, error)
}

// UnimplementedAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (*UnimplementedAPIServer) GetUser(ctx context.Context, req *UserID) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedAPIServer) NewUser(ctx context.Context, req *UserInfo) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewUser not implemented")
}
func (*UnimplementedAPIServer) GetAllUsers(ctx context.Context, req *empty.Empty) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllUsers not implemented")
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.API/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetUser(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_NewUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).NewUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.API/NewUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).NewUser(ctx, req.(*UserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetAllUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetAllUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.API/GetAllUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetAllUsers(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _API_GetUser_Handler,
		},
		{
			MethodName: "NewUser",
			Handler:    _API_NewUser_Handler,
		},
		{
			MethodName: "GetAllUsers",
			Handler:    _API_GetAllUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
